# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: app
      
    -run: npm install
      working-directory: app
    -run: npm test -- --coverage
      working-directory: app
      
    -name: upload coverage
     uses:codecov/codecov-action@v1
      
    - run: npm run build --if-present
      working-directory: app
    - run: npm test
      working-directory: app
      
      - name: Deploy
run: |
git config --global user.name 2017314
git config --global user.email u2017314@giki.edu.pk
git remote set-url origin https://6f536b66b7c0ef83e178a820307764760d31cfc8@github.com/${repository}
npm run deploy
env:
user_name: 'github-actions[bot]'
user_email: 'github-actions[bot]@users.noreply.github.com'
github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
repository: ${{ github.repository }}
